[book]
title = "PG Source Code Note"
authors = ["Jason"]
language = "en"

[output.html]
additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/coreele"
git-repository-icon = "fab-github"

[output.html.fold]
enable = true
level = 0
